name: release
on:
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: jesec/flood
          path: flood

      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: loeken/docker-rtorrent-flood
          path: me

      - name: patch dockerfile
        run: cp me/Dockerfile flood/Dockerfile

      - name: patch package.json
        run: cp me/package.json flood/package.json
      - name: patch package-lock.json
        run: rm flood/package-lock.json
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: loeken/rtorrent-flood:4.7.1,loeken/rtorrent-flood:latest
          context: ./flood
          no-cache: true
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: loeken/rtorrent-flood:4.7.1
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: loeken/rtorrent-flood:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'