name: release
on:
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: jesec/flood
          ref: refs/tags/v0.9.8-r15
      - name: patch dockerfile
        run: sed -i 's/docker.io\/jesec\/rtorrent:master/loeken/rtorrent:latest/g' Dockerfile

      - name: patch package.json
        run: sed -i 's/\"loader-utils\"\: \"\^2.0.0\"/\"loader-utils\"\: \"\^2.0.3\"/g' Dockerfile
        
      - name: ls
        run: cat Dockerfile
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: loeken/rtorrent:testing
          context: .
          no-cache: true%   